export const historyJobsList = [
    {
        Id: '001',
        Title: 'Microondas quebrado',
        Vendor: 'José',
        Client: 'Roberta',
        Price: 'R$150,00',
        FromDate: '01/05/2024',
        ToDate: '04/05/2024',
        Category: 'Microondas',
        Description: 'Microondas não está rodando e esquentando',
    },
    {
        Id: '002',
        Title: 'Microondas quebrado',
        Vendor: 'Arthur',
        Client: 'Roberta',
        Price: 'R$150,00',
        FromDate: '06/05/2024',
        ToDate: '09/05/2024',
        Category: 'Microondas',
        Description: 'Microondas não está rodando e esquentando',
    },
    {
        Id: '003',
        Title: 'Microondas quebrado',
        Vendor: 'José',
        Client: 'Roberta',
        Price: 'R$150,00',
        FromDate: '26/09/2024',
        ToDate: '30/09/2024',
        Category: 'Microondas',
        Description: 'Microondas não está rodando e esquentando',
    },
]